workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: تهيئة المشروع سحابياً
        script: |
          # حذف أي إعدادات أندرويد قديمة تسبب تعارض
          rm -rf android
          # إنشاء هيكل أندرويد جديد متوافق مع السحاب
          flutter create . --platforms android
      - name: بناء التطبيق النهائي
        script: |
          flutter pub get
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk